#!/bin/sh
#
# Start/Stop the DC printer services
#
PIDDIR="/afc/var/run"
###################################
PRINTER_PNAME="dcprinter"
PRINTER_BIN="/afc/bin/dcprinter"
PRINTER_INI="/afc/etc/dcprinter.ini"
PRINTER_OPTION="-i ${PRINTER_INI}"

PRINTER_PID="${PIDDIR}/${PRINTER_PNAME}.pid"


# Wait for a process to die
# $1 is process ID
# $2 is max wait time
wait_timer ()
{
    if [ $# -ne 2 ]; then
        return
    fi

    i=0
    while [ -d "/proc/$1" -a $i -lt $2 ]
    do
        sleep 1
        i=`expr $i + 1`
    done
}

start ()
{
    echo "Starting DC Printer Process ..."

    if [ -f ${PRINTER_PID} ]; then
        PID=`cat ${PRINTER_PID}`
        if [ -d /proc/${PID} ]; then
            echo "${PRINTER_PNAME} is already running"
            echo "Stop the current ${PRINTER_PNAME} session first"
            exit 0
        else
            # Remove existing PID file. Probably left over
            # from some unclean termination
            rm -rf ${PRINTER_PID}
        fi
    fi

    LD_LIBRARY_PATH="/lib:/afc/lib:${LD_LIBRARY_PATH}"; \
    start-stop-daemon --quiet --start --name ${PRINTER_PNAME} --exec ${PRINTER_BIN} --background --make-pidfile --pidfile ${PRINTER_PID} -- ${PRINTER_OPTION}
    
}

stop ()
{
  
        
    echo "Stopping Printer Process ..."
    if [ -f ${PRINTER_PID} ]; then
        PID=`cat ${PRINTER_PID}`
        start-stop-daemon --stop --quiet --name ${PRINTER_PNAME} --pidfile ${PRINTER_PID}

        # Wait for the application to exit.
        # Don't wait for too long, as the application may be hung up somewhere
        wait_timer ${PID} 10

        rm -rf ${PRINTER_PID}
    fi

    # On the safe side, kill the application again
    
    /usr/bin/killall -q -9 ${PRINTER_PNAME}
}

status ()
{
    if [ -f ${PRINTER_PID} ]; then
        PID=`cat ${PRINTER_PID}`
        if [ -d /proc/${PID} ]; then
            echo "${PRINTER_PNAME} is running. PID file ${PRINTER_PID}. PID=${PID}"
        else
            echo "${PRINTER_PNAME} is not running"
        fi
    else
        echo "${PRINTER_PNAME} is not running"
    fi
}

# Environment check


if [ ! -x ${PRINTER_BIN} ]; then
    echo "${PRINTER_BIN} is not found or not executable"
    exit 1
fi

if [ ! -d ${PIDDIR} ]; then
    echo "${PIDDIR} does not exist"
    exit 1
fi


case "$1" in
  start)
    start
    ;;

  stop)
    stop
    ;;

  restart)
    stop
    start
    ;;

  status)
    status
    ;;

  *)
    echo "$Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit $?


